<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_085xxxxxxxxxxx</name>
   <tag></tag>
   <elementGuidId>1775aeba-00d6-467b-a85f-4788d948b8ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'no_telepon' and @placeholder = '085xxxxxxxxxxx']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formTambahTendik [name=&quot;no_telepon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'formTambahTendik']//*[@name = 'no_telepon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07683959-b192-40eb-bef3-ee73036c1d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>578f1009-abc4-46c8-9494-bee064090fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_telepon</value>
      <webElementGuid>68d91d3a-98eb-4a59-8786-4b95a7469917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>085xxxxxxxxxxx</value>
      <webElementGuid>810b7d7a-4162-4ec4-ba08-76d583b7e492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>kry-compact-input w-full px-3.5 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:border-[#00A74D] transition-colors</value>
      <webElementGuid>ee85e2a6-beb1-40fc-ac4d-fc3e17936f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7e8eeadcf6571c9bd110a17c4a86174d</value>
      <webElementGuid>9482c6b5-3f6a-4821-ba3c-a31b89347614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'formTambahTendik']//*[@name = 'no_telepon']</value>
      <webElementGuid>2531f190-42ee-4daf-aa3d-8955f3cc236c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'formTambahTendik']//*[@name = 'no_telepon']</value>
      <webElementGuid>eafccaf9-95cf-48e6-9bff-110a26604a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'no_telepon' and @placeholder = '085xxxxxxxxxxx']</value>
      <webElementGuid>7f929ed8-8fe6-481a-9561-63971841e376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
