<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Wali (5)</name>
   <tag></tag>
   <elementGuidId>8c8b75b9-745c-4a46-8faf-f5086ef02362</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_wali_nama</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63cbcb5e-c29a-49cf-ab51-74e3341966a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>32c02925-16cf-437f-b4b5-1e7a4f233273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_nama</value>
      <webElementGuid>af04ba0c-b8b8-42d9-8b21-6b48759880ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c1618d64-3f3c-4c84-a035-9585483072f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_nama</value>
      <webElementGuid>f470e2b3-ad9e-4818-a945-5a089564bb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-385545e73ed65d436f501db591fcb11b</value>
      <webElementGuid>22c9fbc2-ccbd-4bbc-a468-0fa3e0ff34ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_nama']</value>
      <webElementGuid>2e4297d5-5792-434e-a661-1e0a9f0dc814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_nama']</value>
      <webElementGuid>6acf5098-5e51-4ca2-ae38-9fc0ccebbd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'wali_nama' and @id = 'id_wali_nama']</value>
      <webElementGuid>ec66dd1c-59d5-4089-98f0-ebd7fc66f337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
