<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tempat lahir (3)</name>
   <tag></tag>
   <elementGuidId>a86642f1-3dab-449e-9326-f4dc938e1faa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_tempat_lahir']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_tempat_lahir</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9adfbe0d-3d89-4338-a95d-a440ad3b60f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66efcca8-f39f-4ac3-9cc7-2b27a33bc2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempat_lahir</value>
      <webElementGuid>5f6e0230-75b2-47b2-ad41-d4f5055fa39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e30c2230-a0d1-4cd0-b0e0-2f07c2dad32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e5f23aa2-cf2b-4a05-9680-87cd9c4a1ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_tempat_lahir</value>
      <webElementGuid>c57dd499-537e-4423-b1bd-447ab729cf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2ab7921b17c3c6733bc21f02523e299b</value>
      <webElementGuid>5ba92042-0e88-4604-8b81-e8bcaebc96b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_tempat_lahir']</value>
      <webElementGuid>8201dea4-1e3a-45ac-aa35-09ee21d47a86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_tempat_lahir']</value>
      <webElementGuid>8f7c7643-1518-44b9-9eb7-9b2ebc82efb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tempat_lahir' and @id = 'id_tempat_lahir']</value>
      <webElementGuid>ae6e3f3e-d1eb-43d8-808f-e6c6ef5e145d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
