<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password Wali (2)</name>
   <tag></tag>
   <elementGuidId>3393e563-ed66-4133-8d6f-2c19149f5de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_wali_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b350dd2c-c6a4-4e1d-8a99-67a3f3b109e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>50a79260-369a-4df3-b026-65165a664d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_password</value>
      <webElementGuid>fd4370f8-a972-40bd-9f38-0a711d7980ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dda308d6-75e9-448d-8409-e6032827a6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_password</value>
      <webElementGuid>7d7d8c4c-c142-47f5-868e-d4b2c904d006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-105a79fb65b1731673ba27c18e085f28</value>
      <webElementGuid>ae6b6a53-de80-4379-b388-0dd328bb1cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_password']</value>
      <webElementGuid>96c073aa-5472-4ad8-ad53-a9b72c2b8877</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_password']</value>
      <webElementGuid>3cb842d9-07ea-4b37-b26c-aed9de3e8231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'wali_password' and @id = 'id_wali_password']</value>
      <webElementGuid>c3bd0b38-f8cc-4396-905d-66f8cfa920a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
