<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Konfirmasi Password</name>
   <tag></tag>
   <elementGuidId>b71f68e2-0337-491d-b37b-63f17236e089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_wali_password_confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_password_confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcaf23de-efe5-4ace-b1b6-66ad719bf9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>97ee6af0-db23-4f43-bf31-73398c5d3c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_password_confirm</value>
      <webElementGuid>7ef2dad0-6354-4da8-a70c-768bd3e69541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>365dc3fe-7fec-4dce-aa9b-ab0b2d89d2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_password_confirm</value>
      <webElementGuid>135cdd6d-6b3d-490a-b159-79287cd252bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9f24a76c94263603f68f110f14ade25f</value>
      <webElementGuid>2f5a68cf-f874-4759-9752-fea17e33b2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_password_confirm']</value>
      <webElementGuid>8d6b938e-da31-45f1-b0cc-a4d2c48ba2fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_password_confirm']</value>
      <webElementGuid>2c6343c6-dc68-493c-ad7c-78599b8be37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'wali_password_confirm' and @id = 'id_wali_password_confirm']</value>
      <webElementGuid>deb9dc0f-56e1-47c5-aaa8-fa5a184243e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
