<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal lahir (1)</name>
   <tag></tag>
   <elementGuidId>47d32875-a562-4a6f-8a7e-7d42d23e2816</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_tanggal_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_tanggal_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>25021954-5932-40fe-aa95-a71b1661939d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>fd3c6f05-2819-4052-851a-fd8c739649b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tanggal_lahir</value>
      <webElementGuid>bdf192ab-fbd1-464d-a920-ada91932bf19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>13a2c965-9ff9-4d8c-a783-d17079feba10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_tanggal_lahir</value>
      <webElementGuid>70ef0db5-c34f-4c9d-b76c-766b05c1d63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3dd29a9845216d6223df21b35a2c2cee</value>
      <webElementGuid>fdff8cd7-f677-4312-8dd7-271f6c94ef54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_tanggal_lahir']</value>
      <webElementGuid>d79cc0f0-64fa-4ae7-a541-03344d61fbdb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_tanggal_lahir']</value>
      <webElementGuid>fe0cfb46-c6d8-4174-99a0-8eea88b499d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'tanggal_lahir' and @id = 'id_tanggal_lahir']</value>
      <webElementGuid>11692f0b-7bef-4173-8a1d-2238a7aa0929</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
