<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Wali (3)</name>
   <tag></tag>
   <elementGuidId>1dc230d1-be52-4e47-b884-d9abe9dfed4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_nama']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_wali_nama</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80c5461c-5f7a-4eb0-b3f1-8653a9c99c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8baab2f9-8f39-4e4f-89c6-b8dcf7af1197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_nama</value>
      <webElementGuid>0c6c3e08-4bec-44d2-8d51-adb6edfea0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1db3d05d-01d8-4266-a6f9-54e51bf7e579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_nama</value>
      <webElementGuid>15e8600b-1cf7-446f-a57b-91022f4c5fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-385545e73ed65d436f501db591fcb11b</value>
      <webElementGuid>6bcd6752-5ed5-4256-8d59-f463dd0ffe7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_nama']</value>
      <webElementGuid>48ef9125-b375-4004-be01-6ff3fa52af10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_nama']</value>
      <webElementGuid>6625cbe7-ae4f-4d18-a135-b2f0f50c0169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'wali_nama' and @id = 'id_wali_nama']</value>
      <webElementGuid>73e1de28-01e1-47a5-9ac5-e55fa0a9efda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
