<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Wali (3)</name>
   <tag></tag>
   <elementGuidId>e17fa7e3-f0fd-40f9-9606-4ebd9597fabb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_wali_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5ea50f9-3b9c-4667-a0ff-71936e4fc0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ac60ea7e-bbb8-4330-bc38-fe904e8623aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_email</value>
      <webElementGuid>48e99a11-0986-44d2-9d87-9563d97e82e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3220d257-582d-45a3-93c7-7d406caccf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>320</value>
      <webElementGuid>0a903731-82ca-439e-a03a-012a2d727cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_email</value>
      <webElementGuid>8d75af09-d45b-44cf-a0bd-4902f250496a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d234b771c3f9807c0be6e8cd907c166f</value>
      <webElementGuid>155e7739-42ea-41e0-b2b1-dc212a13be99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_email']</value>
      <webElementGuid>53baf8de-4fed-4eea-89ac-7b63fdfc79ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_email']</value>
      <webElementGuid>03789944-2e11-44ff-99b9-888cba4a0112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'wali_email' and @id = 'id_wali_email']</value>
      <webElementGuid>9bf51980-2206-4b66-8f8b-dfc8a3832882</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
