<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asal sekolah (2)</name>
   <tag></tag>
   <elementGuidId>34036724-c12e-4f29-aafd-49626106c063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_asal_sekolah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_asal_sekolah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>907f215d-05bd-45a5-842b-bd287a425bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41ccf6d1-46da-49bd-a436-245d7f78a1b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asal_sekolah</value>
      <webElementGuid>1717bdc5-b8b3-4002-a630-9c8647eab680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1731cbeb-0f78-4621-b1f7-19be8adaf28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>78cdabe0-4737-4c16-85f5-f9ad327bbc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_asal_sekolah</value>
      <webElementGuid>f738e683-522f-4391-9f3c-1a616a684a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-74e7a7f5db83cb84262a956467c9f092</value>
      <webElementGuid>1abeeaf9-2b59-4351-b13c-0593d934fd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_asal_sekolah']</value>
      <webElementGuid>1d95f6de-cc7d-4ab1-8d75-13752347620a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_asal_sekolah']</value>
      <webElementGuid>d18d503a-8c15-4309-a50d-dcdb50d2997f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'asal_sekolah' and @id = 'id_asal_sekolah']</value>
      <webElementGuid>9b3bd55e-fbce-444d-8e8c-94b3bd9d0308</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
