<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username Wali (6)</name>
   <tag></tag>
   <elementGuidId>5c678a30-e3a6-442f-9a50-81fae16ec29c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_wali_username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba1c6b63-61a2-4a20-8337-1fc2b4883c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84167832-9025-48c2-a4aa-30ded0ffd023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_username</value>
      <webElementGuid>a14742dc-f127-4b1b-b266-aede3fa28811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>18cae18c-865f-4ef0-acf2-0612d44ad1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_username</value>
      <webElementGuid>131e4702-921b-4b5c-a344-547d6ecbe145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fbebb278efe1f20f170c64db05874fd9</value>
      <webElementGuid>ea6f403f-b5c6-4ca1-b810-b246f82ea1ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_username']</value>
      <webElementGuid>0acb78ac-aa79-4fa3-9e59-44f72d796b5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_username']</value>
      <webElementGuid>a8618be7-8e77-4a76-8b7d-7e4d4c6f3796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'wali_username' and @id = 'id_wali_username']</value>
      <webElementGuid>3c28bc42-8fb8-4e38-83ea-b663beb73eba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
