<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal lahir</name>
   <tag></tag>
   <elementGuidId>43537169-585a-484c-b841-c237610650e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_tanggal_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_tanggal_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1cbdeca-9e24-4aab-a26f-089eff20d701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>8280c6e3-280e-4455-8936-02d75bf64003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tanggal_lahir</value>
      <webElementGuid>b9ff845b-1abe-460a-a9ad-7bb1ef58e7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>730c0787-b944-4336-89b6-e3690ce660d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_tanggal_lahir</value>
      <webElementGuid>8d93cb89-f401-45cd-b5c0-6aa7fe75600b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3dd29a9845216d6223df21b35a2c2cee</value>
      <webElementGuid>18646ec9-83ff-4530-ab07-d4e286c79dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_tanggal_lahir']</value>
      <webElementGuid>914557d0-bc5b-4a8a-b9ee-61306a26f4c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_tanggal_lahir']</value>
      <webElementGuid>dcae4533-57eb-4c50-b3e7-83fdc4169045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'tanggal_lahir' and @id = 'id_tanggal_lahir']</value>
      <webElementGuid>a42dd876-236f-49fe-b5aa-f661b480ec96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
