<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password Wali (4)</name>
   <tag></tag>
   <elementGuidId>938f9f6e-413e-48e2-b928-68f3b924ee06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_wali_password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db90b154-0a7b-428e-ba81-d91fd4bea763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6f3e017f-b9cc-45e4-b3ab-ce7b624f8d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_password</value>
      <webElementGuid>57233cf5-c469-4175-9474-c8e3bd0d91b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>35b84712-2a69-4590-b1cc-95fc4bb83da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_password</value>
      <webElementGuid>1f34cccc-2d4e-44df-ac2c-2c4676f16b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-105a79fb65b1731673ba27c18e085f28</value>
      <webElementGuid>a5220adc-0d58-4dcb-bb60-89fbf4d833f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_password']</value>
      <webElementGuid>45c94016-dfa8-40dc-bcd0-ea84d04c8fde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_password']</value>
      <webElementGuid>c9ed0533-1ca1-4354-a93f-5c793ae21240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'wali_password' and @id = 'id_wali_password']</value>
      <webElementGuid>28d1271c-30e5-4ded-afa7-e3401c78dcbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
