<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama lengkap (1)</name>
   <tag></tag>
   <elementGuidId>81da605e-dc77-4714-be37-d82ea9390aed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_nama_lengkap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_nama_lengkap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb164cb1-d95a-4571-924e-f0580a4de9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4df5176-98f6-4c81-b781-e695042649f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_lengkap</value>
      <webElementGuid>696331e2-9a5b-43ed-88a3-d0491f6bd49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d8ef6528-f55c-44c5-9b52-6f3d9aa24197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>703fe190-30a3-4f9e-b7c8-9e52649a970a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_nama_lengkap</value>
      <webElementGuid>4696898c-19b8-41d3-bea3-d52a14bf96e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0991b2e56589fae3f3da650ba0627e05</value>
      <webElementGuid>99a238ea-0c5b-4842-92a1-56ab7821d63b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_nama_lengkap']</value>
      <webElementGuid>2ecd8b03-2d08-460f-ad50-924c7e4ea4d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_nama_lengkap']</value>
      <webElementGuid>d091d8af-f17c-4298-b3ee-f5f6a56a033d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nama_lengkap' and @id = 'id_nama_lengkap']</value>
      <webElementGuid>acb2cda0-6b57-4317-85ab-6b6240db9897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
