<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username Wali (2)</name>
   <tag></tag>
   <elementGuidId>007e33e5-28af-41a6-b38a-56842d6b31d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_wali_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87211136-b5c3-4b06-8855-8fad09833410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>670b52f8-50f4-4ad0-8c0d-0b54fd67356d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_username</value>
      <webElementGuid>81a68b45-3a59-47e6-91b3-fdfa8fcc8312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0a0785b2-1c82-4328-aff9-e2dd51f08a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_username</value>
      <webElementGuid>3d4db2bc-2e64-45b3-933a-3fc272ec22fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fbebb278efe1f20f170c64db05874fd9</value>
      <webElementGuid>0b679e67-a05a-4d90-808a-4bc96d423b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_username']</value>
      <webElementGuid>1de8ddf7-dcc9-40e1-a78f-5c9965b7d179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_username']</value>
      <webElementGuid>939563a0-3da5-4086-b7f8-a714853e0f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'wali_username' and @id = 'id_wali_username']</value>
      <webElementGuid>0d5329c9-fa99-400d-a104-7a152eaf4e92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
