<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asal sekolah</name>
   <tag></tag>
   <elementGuidId>90f7a627-84f9-4d21-ba92-19aca35cbae4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_asal_sekolah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_asal_sekolah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>665f1f9c-6bcc-407c-82df-cf0b42c79d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51e30b15-997c-4726-9fb8-a008fc98e875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asal_sekolah</value>
      <webElementGuid>e40ad096-713c-476e-85f6-f3ba2cb63b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ca7e9506-4155-4f64-97e5-175e4fc0adfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>aa0e4be5-a46d-4384-9492-6b3a831f66bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_asal_sekolah</value>
      <webElementGuid>a034f8e6-1508-41e6-9e1d-b6e1cec861ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-74e7a7f5db83cb84262a956467c9f092</value>
      <webElementGuid>0af177e9-5ee6-4069-a9fa-355889b3440e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_asal_sekolah']</value>
      <webElementGuid>9f8c6047-2aa5-4af3-a030-24ebb9f34f24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_asal_sekolah']</value>
      <webElementGuid>183854db-3674-4b7c-a0a3-d6f8ffc64548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'asal_sekolah' and @id = 'id_asal_sekolah']</value>
      <webElementGuid>aae055a2-ad73-4f0b-87fb-6b73ff2fe0d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
