<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asal sekolah (3)</name>
   <tag></tag>
   <elementGuidId>64e25e34-14aa-40f4-84d0-203276c765a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_asal_sekolah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_asal_sekolah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da0dd828-adaf-4876-ab09-058aa7ae96e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c06ca18c-0fc7-4c19-aadf-58685119ee96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asal_sekolah</value>
      <webElementGuid>54b1df14-a763-4aa8-afe9-0a6bf2faca78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>149f999d-62e7-4048-b47d-fe9d4b15796e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8acd2079-402d-477d-9933-acb63f5d4224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_asal_sekolah</value>
      <webElementGuid>866cd1ef-20ce-4fa4-8192-9bf1c313f4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-74e7a7f5db83cb84262a956467c9f092</value>
      <webElementGuid>029d4ac4-d561-4c69-807b-99d66198696a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_asal_sekolah']</value>
      <webElementGuid>e6042d32-834b-4bbc-b660-74456de713e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_asal_sekolah']</value>
      <webElementGuid>095720f2-a453-459e-9ef6-814ef7d4422a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'asal_sekolah' and @id = 'id_asal_sekolah']</value>
      <webElementGuid>22038cdf-d12f-498b-90aa-5658ae07aee7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
