<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nis (1)</name>
   <tag></tag>
   <elementGuidId>4200ecff-116f-4dbb-b484-d88d0867bfa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_nis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_nis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1989278e-f0a4-475b-a403-0f21a61a6224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>56815dc0-34b9-466f-9d4f-4df8f4389bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nis</value>
      <webElementGuid>64d8841b-ed49-40fb-958c-33bf529cf5db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9c633fef-c814-4098-a680-52f38f3b39ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b689c1e5-cc2f-4e57-a832-48c9e431350c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_nis</value>
      <webElementGuid>6ffd530b-1278-4a19-a3b3-059ce10bd947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0991e40513b0a26afc554ea5a8b4f7f2</value>
      <webElementGuid>abad8786-59b1-4b6b-8cb2-aebeecefc4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_nis']</value>
      <webElementGuid>0080d14f-1c9f-47e0-bf26-dcc932b4b044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_nis']</value>
      <webElementGuid>d93d1551-6a54-4521-8610-9e98445df86b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nis' and @id = 'id_nis']</value>
      <webElementGuid>a4ce5ef5-820a-462d-9034-7590ad5c8a23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
