<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tempat lahir (1)</name>
   <tag></tag>
   <elementGuidId>6ba995d4-7b1b-44c4-8327-2edc1e4e1d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_tempat_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_tempat_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9817c0a-a477-43c8-bd3e-7fd26f283086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2cbaa73b-9d21-4b95-8ccd-340bf9da52ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempat_lahir</value>
      <webElementGuid>8c57b1fa-3f9e-46da-8803-ed45da7925cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>70761fa0-e27d-428a-ae15-077a04c6389a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>72139186-a98e-4653-91ac-82680fdaa245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_tempat_lahir</value>
      <webElementGuid>af730b32-fbf9-4be1-aee8-de65424f7893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2ab7921b17c3c6733bc21f02523e299b</value>
      <webElementGuid>e2755d78-c922-43a2-b60b-0755d3c922a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_tempat_lahir']</value>
      <webElementGuid>8e6e74ad-f23d-472d-8745-94843cefe6e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_tempat_lahir']</value>
      <webElementGuid>94503f36-881b-4769-ba56-b4d3afd2486a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tempat_lahir' and @id = 'id_tempat_lahir']</value>
      <webElementGuid>5ee94e05-6a6d-4efe-8472-32ea9ce7b5b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
