<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username Wali (5)</name>
   <tag></tag>
   <elementGuidId>be073ba3-ccd2-4ae6-abd4-4e3344bd9c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_wali_username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89a94184-a554-40ba-8fc5-1f775668078d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1af295cd-f8ec-42d5-856b-c15038b1dab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_username</value>
      <webElementGuid>8d709f90-1c65-4289-97a2-f821b00c9af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a6e4fbcf-52c2-44db-8267-587e9659aeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_username</value>
      <webElementGuid>ad471fb8-703e-4f44-b760-f1d33c762d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fbebb278efe1f20f170c64db05874fd9</value>
      <webElementGuid>b73290cf-00d3-42f4-aea8-cb187d5576c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_username']</value>
      <webElementGuid>ab35c6aa-90e0-4898-8ebe-e51c6a19ca1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_username']</value>
      <webElementGuid>5054074c-00c0-4bb1-9564-a778ac8caebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'wali_username' and @id = 'id_wali_username']</value>
      <webElementGuid>96dc24cd-a330-4bd9-8fd5-1f4a5c9e7f2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
