<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username Wali (3)</name>
   <tag></tag>
   <elementGuidId>c75f26ab-f77e-4838-9b9f-81b40515f181</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_wali_username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42787ac8-071e-490f-8aba-36c4130becee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>058fd26f-7940-4e02-a151-bf73a1d97026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_username</value>
      <webElementGuid>20a0e59e-cbac-430e-83ec-8b54bc816e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e3334964-3831-4110-a939-9d3ba1622450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_username</value>
      <webElementGuid>a8b0575f-db36-4ae9-a14d-746524739a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fbebb278efe1f20f170c64db05874fd9</value>
      <webElementGuid>94c57a47-8b1c-47ef-a76a-aaf9baf5c1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_username']</value>
      <webElementGuid>e78812af-f939-495b-9a4b-af5d6a2cf16c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_username']</value>
      <webElementGuid>531a9570-3523-41c8-8636-90ea314f47b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'wali_username' and @id = 'id_wali_username']</value>
      <webElementGuid>cefe2cae-988d-4b7b-95bb-7e54a64d9541</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
