<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Wali</name>
   <tag></tag>
   <elementGuidId>bd98036a-62df-4200-8117-9445d0abb810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_wali_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>635ced1e-aa3e-4b7f-9894-54de940d9159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8ef1cfc1-a023-457c-907f-bdd8ba89253e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_email</value>
      <webElementGuid>5d9f8cb6-6c93-48e2-aa5e-18f6dc9b1319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6a026256-87eb-4303-bf1a-fa23569b4b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>320</value>
      <webElementGuid>cd3b3973-c94a-4ab0-a348-1da66021842b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_email</value>
      <webElementGuid>1eb74b62-111c-427d-9266-87661ddd6ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d234b771c3f9807c0be6e8cd907c166f</value>
      <webElementGuid>a3d73648-9e87-444c-b1e9-dca2eebe6cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_email']</value>
      <webElementGuid>9c3719a0-91df-485f-8abb-dbdf1348cd33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_email']</value>
      <webElementGuid>86e88ee1-4c6b-490e-a820-c445302c35ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'wali_email' and @id = 'id_wali_email']</value>
      <webElementGuid>a1289dca-a21d-4c87-a53c-1adc89162c58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
