<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asal sekolah (1)</name>
   <tag></tag>
   <elementGuidId>91b1ece9-e62b-48e1-958c-97b8d228d574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_asal_sekolah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_asal_sekolah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16deb60d-2270-4d75-8790-5f419ee62f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86dea6b6-c0e1-485f-a761-8fac1cec0bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asal_sekolah</value>
      <webElementGuid>f52603eb-81ca-49cb-be74-e1e67c3ad015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>56996bf4-8823-40d2-aae9-a480fd67b202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>fc35d8fc-6f95-4136-802c-313b85f7294d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_asal_sekolah</value>
      <webElementGuid>ec38ce5a-31ce-466d-a838-74f76fb061b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-74e7a7f5db83cb84262a956467c9f092</value>
      <webElementGuid>164666da-9980-4f01-b429-2479f612ec97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_asal_sekolah']</value>
      <webElementGuid>8c9517a1-236b-470c-9327-64b22abdeec9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_asal_sekolah']</value>
      <webElementGuid>44ed9770-768d-4987-9226-fdbd3af94abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'asal_sekolah' and @id = 'id_asal_sekolah']</value>
      <webElementGuid>0369e1fd-690c-447b-b9aa-d33d86442a9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
