<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Alamat Wali</name>
   <tag></tag>
   <elementGuidId>53d7caec-f639-4bb7-958c-8d61c4ea5d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_wali_alamat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_wali_alamat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>99f608bb-d9c7-470d-83ac-96772c395501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wali_alamat</value>
      <webElementGuid>e9b53641-e344-49c1-a56c-7c0509230f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>1a454d3a-7577-4de6-9d3d-1184c8defd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d31baf73-c4ec-4a50-9642-100b46f00548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f22b4b62-38b8-4a9d-b622-6270d2c77641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_wali_alamat</value>
      <webElementGuid>b5e14af9-bedb-4d45-9a9d-48ae48b159c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-65a67dbfecdc9d6a9b17a7d9529cff61</value>
      <webElementGuid>430a4f44-bd21-4270-84ed-0e56c41c7f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_alamat']</value>
      <webElementGuid>07292ee6-d523-48a5-a819-3cd86f3c6ad5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_wali_alamat']</value>
      <webElementGuid>b756c8da-e087-44aa-b90e-6cfa7aca3806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'wali_alamat' and @id = 'id_wali_alamat']</value>
      <webElementGuid>1b227bb2-14a9-4cda-a618-98869f68ee4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
