<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Kelola</name>
   <tag></tag>
   <elementGuidId>5e8ee609-6ae0-47cc-856f-4bb2770a94b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.kelas-card:nth-child(1) .rounded-md.inline-flex.transition-colors[type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' kelas-card ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and contains(concat(' ', normalize-space(@class), ' '), ' inline-flex ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-colors ') and (@type = 'button')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0aa3453c-a608-40ac-9150-46f36935c4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>32f6d394-49f4-485a-bc4b-7c2a66464c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleKelolaMenu('menu-aktif-154')</value>
      <webElementGuid>9e64293e-1d1b-4336-ac4e-15fe1197b448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center gap-1 bg-[#E6F6ED] text-[#00A74D] rounded-md font-semibold hover:bg-[#d4f3e3] transition-colors h-6 px-2.5 text-[11px]</value>
      <webElementGuid>51e8f192-cc22-411e-a271-c0e94db2ccaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Kelola
                                    >
                                </value>
      <webElementGuid>100acb75-5e23-48c1-a06d-e4cbc398848c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5b87b207404c48fdd942794a2d9cbc46</value>
      <webElementGuid>27fdaf96-5ac4-48cb-b6b8-f0e436be670c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' kelas-card ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and contains(concat(' ', normalize-space(@class), ' '), ' inline-flex ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-colors ') and (@type = 'button')]</value>
      <webElementGuid>10fea991-4447-4256-bc25-08d43b8c4a53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' kelas-card ') and (position() = 1)]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ') and contains(concat(' ', normalize-space(@class), ' '), ' inline-flex ') and contains(concat(' ', normalize-space(@class), ' '), ' transition-colors ') and (@type = 'button')]</value>
      <webElementGuid>6658d165-1aab-4c79-a602-40e8cd79a55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                    Kelola
                                    >
                                ' or . = '
                                    Kelola
                                    >
                                ')]</value>
      <webElementGuid>1e7bed42-3175-486a-9c18-e51c2626862b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
