<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>a6b5ed1f-98ac-4944-a0d0-fd4819ed42aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formEditKelas [type=&quot;submit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'formEditKelas']//*[@type = 'submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b748276-dd4a-4bcd-b14d-d2d34c564652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>7281bd91-3c0e-442a-9f87-b07863513d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 px-4 py-2 bg-[#00A74D] text-white rounded-lg text-sm font-semibold hover:bg-[#008f42] transition-colors shadow-sm</value>
      <webElementGuid>963c2ca4-d487-4803-96d6-591d61914a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>62f6eced-3d5e-4903-966c-86938cbf73b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-5bb9867f3d339e0e79adffaea6537288</value>
      <webElementGuid>82018dbc-545f-481c-9993-1f307dce6261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'formEditKelas']//*[@type = 'submit']</value>
      <webElementGuid>3f1b1ce0-b305-42a9-ab49-d7e624ac95a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'formEditKelas']//*[@type = 'submit']</value>
      <webElementGuid>8f434eca-d205-4e7a-9f8f-eebe96839fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>78419838-4f9c-41b6-93b6-90e81595b54b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
