<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Arsipkan_1</name>
   <tag></tag>
   <elementGuidId>b45ef2da-8469-4617-8310-5810ae8cd667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formArsipKelas [type=&quot;submit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'formArsipKelas']//*[@type = 'submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8591c82e-517b-4926-a54e-34847813cc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8aa171b0-fc88-4103-928d-cb4c7d6219a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 px-4 py-2 bg-amber-600 text-white rounded-lg text-sm font-semibold hover:bg-amber-700 transition-colors shadow-sm</value>
      <webElementGuid>65349bda-0d6c-4e44-b53b-e68a0535d335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Arsipkan</value>
      <webElementGuid>bfe5e8f5-24d9-4d20-8934-5b2771df2dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-97b37ad9d56e998b106540339feb1377</value>
      <webElementGuid>6f50d1ef-3b8f-4259-b240-485b2c7dbcfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'formArsipKelas']//*[@type = 'submit']</value>
      <webElementGuid>8f83e254-675c-4c4c-9068-bf7247cdeb75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'formArsipKelas']//*[@type = 'submit']</value>
      <webElementGuid>c68ed4df-2a90-48b9-8f2d-fa21bf259748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Arsipkan' or . = 'Arsipkan')]</value>
      <webElementGuid>b01a32d7-4a4e-4b01-a392-9cb4b525547a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
