<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hapus_1</name>
   <tag></tag>
   <elementGuidId>e42240df-9ade-4a71-8c0a-699c5e091e35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formHapusKelas [type=&quot;submit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'formHapusKelas']//*[@type = 'submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9dc4f51a-aa5e-4d05-b32c-99b6f6155ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>46573549-32db-4b4b-8ddf-3f30e1f240fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 px-4 py-2 bg-red-600 text-white rounded-lg text-sm font-semibold hover:bg-red-700 transition-colors shadow-sm</value>
      <webElementGuid>f85305c1-58ff-4db5-8bd1-f08d6e590d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hapus</value>
      <webElementGuid>52746c7e-40bd-4265-9c64-be57567c142f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d97d2409e5c4d4268054ca98c99a5a0a</value>
      <webElementGuid>fc316765-add7-4a5a-9c8a-77b832c47c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'formHapusKelas']//*[@type = 'submit']</value>
      <webElementGuid>e022b676-f039-49ac-a276-08c1308f88f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'formHapusKelas']//*[@type = 'submit']</value>
      <webElementGuid>4cc332a7-2b4a-45fa-bbb3-50bbed6b7386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Hapus' or . = 'Hapus')]</value>
      <webElementGuid>00d3c873-8aca-4d77-bf46-4d2025d50330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
