<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>ea7b7194-9af0-46eb-9186-7cb671266212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.kelas-card:nth-child(1) [onclick=&quot;openModalEditKelasFromTrigger\(this\)&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' kelas-card ') and (position() = 1)]//*[@onclick = 'openModalEditKelasFromTrigger(this)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc4e6b0b-0228-4d59-a499-5a3491b8c3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5424989-27ed-4d84-939b-545780e0feec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openModalEditKelasFromTrigger(this)</value>
      <webElementGuid>fa773549-03d0-4cfc-a95c-56b2d3587fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kelas-id</name>
      <type>Main</type>
      <value>118</value>
      <webElementGuid>467d8a93-553a-42ad-b4d5-d95c00910377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tingkat-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e110812c-cdc8-4c65-a53a-053b71523be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nama-kelas</name>
      <type>Main</type>
      <value>1B</value>
      <webElementGuid>1de19baa-f050-49aa-8696-dac811745236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kapasitas</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>99e26518-df8c-4eaa-9040-818080d6644e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wali-guru-id</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>c5c233d0-91ed-415d-b197-0d212438b1e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tahun-ajaran-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d22dc13e-4181-4f9c-bec4-49c9a7dd8d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-left px-3 py-2 text-xs text-slate-700 hover:bg-slate-50</value>
      <webElementGuid>dd955f3f-60dc-4be9-8013-3b832298fa97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Edit
                                    </value>
      <webElementGuid>3f67ddab-d763-4d51-81fc-13c39f268c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-855b1ab0786c5324ec5a98dc704555e5</value>
      <webElementGuid>3300e066-606c-427b-86f1-ccab8a705a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' kelas-card ') and (position() = 1)]//*[@onclick = 'openModalEditKelasFromTrigger(this)']</value>
      <webElementGuid>1ecdee28-5dd1-4b0a-8bae-e36b6fe8592c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' kelas-card ') and (position() = 1)]//*[@onclick = 'openModalEditKelasFromTrigger(this)']</value>
      <webElementGuid>229d2588-7b6e-43ac-af51-74c29aeef7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                        Edit
                                    ' or . = '
                                        Edit
                                    ')]</value>
      <webElementGuid>10a1cf30-e132-456d-aaca-5170399ff1fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
