<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_kapasitas</name>
   <tag></tag>
   <elementGuidId>639c530d-d49c-4844-9600-e928b803dffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[action=&quot;\/pembelajaran\/rombel\/tambah\/&quot;] [name=&quot;kapasitas&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@action = '/pembelajaran/rombel/tambah/']//*[@name = 'kapasitas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1daa6a6e-69d0-4947-8c50-616fddf6c7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e24ba90e-c2f9-43c5-9327-92a3d8e73729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kapasitas</value>
      <webElementGuid>e31be7f3-7b4a-4a5d-9609-18766eaac247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>61f30ae2-94ff-488c-ae43-548f08c5589c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4d6811b0-74e7-4fe2-b7e8-9fb2902a78f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>f14d632b-f564-4f5d-9b59-d336668a0a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 py-2 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#00A74D] focus:border-[#00A74D] transition-all</value>
      <webElementGuid>ea2e1d08-2ca7-40ec-a179-ff669a6bf291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-91c4ec84d4898b35229b011fa00139b8</value>
      <webElementGuid>7806652e-ab67-4dad-b998-c2121de007b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@action = '/pembelajaran/rombel/tambah/']//*[@name = 'kapasitas']</value>
      <webElementGuid>efdd3ed1-1b05-4476-8bc2-c41dc8dec9d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@action = '/pembelajaran/rombel/tambah/']//*[@name = 'kapasitas']</value>
      <webElementGuid>e4eb7517-156b-42d5-9c90-17fe54b3c2cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'kapasitas']</value>
      <webElementGuid>284c0771-ba94-412b-928f-5360fc587fc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
