<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__</name>
   <tag></tag>
   <elementGuidId>1fa02a15-0b33-487c-adb9-d5b932b6c614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.kelas-card:nth-child(1) span.text-xs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' kelas-card ') and (position() = 1)]//span[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-xs ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c5ec5e6d-732f-4e28-b8ad-d7f1ecd5fbcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xs</value>
      <webElementGuid>f1189ef1-4858-45e1-922a-515ed2791f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>></value>
      <webElementGuid>e33391c6-4d22-41bf-b820-7b4bbcc9ef20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6c3ed99432c7727e6e6f0bfdcb8b47ee</value>
      <webElementGuid>109b4614-f792-4e98-8f37-d24734dc499b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' kelas-card ') and (position() = 1)]//span[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-xs ')]</value>
      <webElementGuid>1d988c97-12de-4bc4-83a0-d26fdfbc81df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' kelas-card ') and (position() = 1)]//span[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-xs ')]</value>
      <webElementGuid>79952a1c-1878-497a-ba1d-76b7f0aa5b74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '>' or . = '>')]</value>
      <webElementGuid>8d6e7bb9-bd7c-4371-9294-fe5be6796bcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
