<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_0812xxxxxxx</name>
   <tag></tag>
   <elementGuidId>b6dea935-84ea-4fc6-bf6c-bbcdee612a72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'no_telepon' and @placeholder = '0812xxxxxxx']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#formTambahGuru [name=&quot;no_telepon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'formTambahGuru']//*[@name = 'no_telepon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1daf6cbd-ca47-4d48-85d9-b12c6cb2c966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4081bab5-4db4-4b3c-9009-e8d8f3560872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>no_telepon</value>
      <webElementGuid>29678b34-852f-465d-a6eb-a52b18a433c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>0812xxxxxxx</value>
      <webElementGuid>45530235-e62b-4f27-b118-d1f764615af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>compact-control w-full px-3.5 py-2.5 border border-gray-300 rounded-lg text-sm text-gray-700 placeholder-gray-400 focus:outline-none focus:border-[#00A74D] transition-colors</value>
      <webElementGuid>60fa7cab-1fc0-42f6-bcbe-b917476550aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4106af86135b6bb5aeb6981e3f4b7d94</value>
      <webElementGuid>6fc70b52-7c26-4c29-9b6b-643871d1dfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'formTambahGuru']//*[@name = 'no_telepon']</value>
      <webElementGuid>2eeb2c28-4ff0-4047-8f84-358f4a5e7bec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'formTambahGuru']//*[@name = 'no_telepon']</value>
      <webElementGuid>48027827-54dc-4c62-9573-8f7077c4fbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'no_telepon' and @placeholder = '0812xxxxxxx']</value>
      <webElementGuid>485cf83d-51ca-4c9a-bac7-3dec4ebaee69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
