<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_edit</name>
   <tag></tag>
   <elementGuidId>ab8e249f-e097-45a7-83d1-3355e315e70b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'edit' or . = 'edit')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-role=&quot;Guru&quot;] .material-symbols-outlined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-role = 'Guru']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' material-symbols-outlined ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4dbaa2c1-85b4-4a24-8605-2a1f8d487c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-symbols-outlined</value>
      <webElementGuid>4e689817-9bec-4511-bdac-b4705faf8ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>83a64ce4-d86b-43bc-b90e-e76bac32e80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3793e6892fc784e469bf52818cbdbb8d</value>
      <webElementGuid>2ccb99b0-9f52-407b-a301-96275a6b119f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-role = 'Guru']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' material-symbols-outlined ')]</value>
      <webElementGuid>e18299b5-6f92-491b-a21f-eca110656c0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-role = 'Guru']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' material-symbols-outlined ')]</value>
      <webElementGuid>4782177a-1719-4022-95a7-1f450e9be8ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'edit' or . = 'edit')]</value>
      <webElementGuid>f8436a3e-a5dd-45a4-92b4-c956b0817073</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
