<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hapus</name>
   <tag></tag>
   <elementGuidId>e7dd6b18-d8a1-44a0-a74c-1377a9394302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#formHapusMapel [type=&quot;submit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'formHapusMapel']//*[@type = 'submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0bfefa01-1a79-470e-976f-5daedeb4b8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c421a98c-4d36-4fa8-9df2-e35574183bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-1 px-4 py-2.5 bg-red-600 text-white rounded-lg text-sm font-semibold hover:bg-red-700 transition-colors shadow-sm</value>
      <webElementGuid>8e8623a7-1ec9-486a-a66f-3f2002f54379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
          Hapus
        </value>
      <webElementGuid>7b0c5be2-e363-4a68-8c25-43560cc8c805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a56b1f6e80fde166a94e31a581edcd44</value>
      <webElementGuid>d9f415e0-4388-4cf3-85ba-2a18bfd49961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'formHapusMapel']//*[@type = 'submit']</value>
      <webElementGuid>e923ddc5-2d4c-4b4f-9933-fbb8e2ec0c4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'formHapusMapel']//*[@type = 'submit']</value>
      <webElementGuid>9356200f-e021-4dca-9807-e236550d2416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = '
          Hapus
        ' or . = '
          Hapus
        ')]</value>
      <webElementGuid>9a4fdad0-f8f4-4e62-98d9-b47de5fe79a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
