<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_edit_nama_mapel</name>
   <tag></tag>
   <elementGuidId>28160a63-d801-4f9a-a18a-7d1650a585b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'edit_nama_mapel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit_nama_mapel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83764612-7cbc-4a12-b7aa-5cdb97f14a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1848d9c2-0252-4635-a61c-c220feef5647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_nama_mapel</value>
      <webElementGuid>1b78b675-1a9f-4085-b154-61865a2082d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_mapel</value>
      <webElementGuid>9ea2782e-5332-43dc-910f-ee2973b3ee7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#00A74D] focus:border-[#00A74D]</value>
      <webElementGuid>844574a5-032d-483f-97cb-1db5d9b4eae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8a827b24592f0b190af23a63642a21f3</value>
      <webElementGuid>490172f0-52fd-4bbe-a5ec-4dc97d95273a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'edit_nama_mapel']</value>
      <webElementGuid>3323d0bd-8c71-4afc-8050-0dc0b65c8716</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'edit_nama_mapel']</value>
      <webElementGuid>f517e572-1e32-4cdb-b8eb-97cdb1e354a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit_nama_mapel' and @name = 'nama_mapel']</value>
      <webElementGuid>6f314c17-e57d-4ab4-9356-c87c5b10c958</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
