<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_edit_kode_mapel</name>
   <tag></tag>
   <elementGuidId>48ea772c-b0e7-4cdb-a0ab-e5044a06cbc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'edit_kode_mapel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit_kode_mapel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a7eb90eb-f9cc-4823-b5ce-e7c091bca364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ad44361-9618-4c42-9851-e5c3abb6263a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_kode_mapel</value>
      <webElementGuid>7ddf3af7-c4e5-4a2a-8ea1-8afb761eb57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kode_mapel</value>
      <webElementGuid>9d92b76f-78f1-4996-ad67-0dd299c548d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#00A74D] focus:border-[#00A74D]</value>
      <webElementGuid>2a24c285-e8ee-4560-bb06-6757601148ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-e85f0587f537043672c16d2d12105ee6</value>
      <webElementGuid>9208e8fa-68dc-4221-9f63-db2a0e6cdea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'edit_kode_mapel']</value>
      <webElementGuid>af3752df-2a2b-4869-ae6a-a64d46864469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'edit_kode_mapel']</value>
      <webElementGuid>6253c233-0f37-4e25-8e9a-07aefc759739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'edit_kode_mapel' and @name = 'kode_mapel']</value>
      <webElementGuid>e8428cad-6f7c-4fe2-a1af-fe4a812d519b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
