<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_edit_keterangan</name>
   <tag></tag>
   <elementGuidId>be9a981c-582d-4efd-80d6-446612911257</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'edit_keterangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit_keterangan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3a5c39df-8c9b-43d4-9cc6-283a8e7c2255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_keterangan</value>
      <webElementGuid>68d9b57a-1ce3-4719-a3a3-45736e566dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>668c4236-2eae-4344-b2cb-8350c872e24c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>99371a97-6a88-4d0b-8069-862224fca5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 border border-gray-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-[#00A74D] focus:border-[#00A74D] resize-none</value>
      <webElementGuid>382745a8-fcbc-4e06-89d2-733848df5dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-507856777625188a3a4f658f16640603</value>
      <webElementGuid>6f92bcca-268e-4711-a70a-cfbbc6eeb229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'edit_keterangan']</value>
      <webElementGuid>89711878-a30a-4aba-99ec-9bd96b2d0b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'edit_keterangan']</value>
      <webElementGuid>fcc67480-97f2-443b-b3ea-edcf113e8206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'edit_keterangan' and @name = 'keterangan']</value>
      <webElementGuid>847f7a0c-267c-4ea6-9795-58c01c6feef9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
