<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ (2)</name>
   <tag></tag>
   <elementGuidId>9b8bec7c-3287-493a-91ef-345bf9e9c19e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/pembelajaran/kurikulum/']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/pembelajaran\/kurikulum\/&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9cd26749-5b61-49be-b7fe-9e0ed7845db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pembelajaran/kurikulum/</value>
      <webElementGuid>460eb394-1a29-495d-8121-d12e024e11b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link sub-link relative pl-6 pr-3 py-2 text-[#64748b] no-underline rounded-[10px] font-medium text-[13px] hover:bg-[#f8fafc] hover:text-[#0f172a] </value>
      <webElementGuid>56fabf63-393f-4868-8884-7c38b575e9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            •
                            Pelajaran
                        </value>
      <webElementGuid>c00e809b-1e65-4b9a-b82b-d7eec8e28431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-866fc43d8ebceadade7caac34536de28</value>
      <webElementGuid>0064e2ae-4d4c-4260-a44f-9da49b2f3121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/pembelajaran/kurikulum/']</value>
      <webElementGuid>3be3fb57-45dd-4b10-a621-7395cd8d1ec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/pembelajaran/kurikulum/']</value>
      <webElementGuid>587775ff-f567-4b49-ba91-737f04efb7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pembelajaran/kurikulum/' and (text() = '
                            •
                            Pelajaran
                        ' or . = '
                            •
                            Pelajaran
                        ')]</value>
      <webElementGuid>7927329d-faa2-4f0d-a46e-3445424a2bb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
