<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>3ee87b5c-ccd1-4182-96e3-9002d36ff41e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/pembelajaran/kurikulum/' and (text() = '
                            •
                            Pelajaran
                        ' or . = '
                            •
                            Pelajaran
                        ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/pembelajaran\/kurikulum\/&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/pembelajaran/kurikulum/']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0cadc9ab-ce19-4c87-a756-617905a1fa51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pembelajaran/kurikulum/</value>
      <webElementGuid>dba579a5-f281-43f0-a200-5ee2905d516e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link sub-link relative pl-6 pr-3 py-2 text-[#64748b] no-underline rounded-[10px] font-medium text-[13px] hover:bg-[#f8fafc] hover:text-[#0f172a] </value>
      <webElementGuid>208e06a4-0079-4b0e-a039-278a80e92631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            •
                            Pelajaran
                        </value>
      <webElementGuid>fd992f3d-e041-4c06-8e60-f9cd5fbe8abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-866fc43d8ebceadade7caac34536de28</value>
      <webElementGuid>d62f2c0a-703e-42f0-bff0-e9a3f8d77ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/pembelajaran/kurikulum/']</value>
      <webElementGuid>a7bfa02a-43b4-4e2a-8323-06f04e462f2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/pembelajaran/kurikulum/']</value>
      <webElementGuid>d9d16e05-8a63-4dcb-bc1f-4d79eefeacf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pembelajaran/kurikulum/' and (text() = '
                            •
                            Pelajaran
                        ' or . = '
                            •
                            Pelajaran
                        ')]</value>
      <webElementGuid>00bf6716-1173-4a8e-83bd-8592b2b13952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
