<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Dashboard</name>
   <tag></tag>
   <elementGuidId>92c6d001-75a2-43ff-8bba-bd398a9cb4ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>aada1c14-9b44-4ef7-b037-8b2e3b3063f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-2xl font-bold m-0 mb-1 text-[#0f172a] leading-tight</value>
      <webElementGuid>a0b152b8-0e3c-4ea3-92bf-41d4998a6159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Dashboard
                </value>
      <webElementGuid>4dba7c9f-cd6f-4e6c-a0e4-2484edb36bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fb3552d99c58948e2bb074c2caec7792</value>
      <webElementGuid>4ca18ad7-9842-44c9-8c92-b814ea4339c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>d56dd200-84b8-44c0-ae59-97ebd133eb72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b60a5a25-6e4b-4447-9f28-03ce9feba343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
                    Dashboard
                ' or . = '
                    Dashboard
                ')]</value>
      <webElementGuid>aea3b21b-ce68-4dcf-9438-97422be3eb36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
