<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No.HP _ Username (40)</name>
   <tag></tag>
   <elementGuidId>f2d225ea-92ed-4d94-b9f7-2ff16ef0a00c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11839ff2-56f1-4847-8b14-ac48c6d5fd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d527a51-f32c-4e56-9022-32b356271622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>84d24a18-95ef-4337-8633-28851ea275a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>120cca91-f807-4677-baee-b02e8e2c7cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No.HP / Username</value>
      <webElementGuid>a075dc49-d8e2-41a3-a331-0a011deee21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>a09dbd24-d056-4927-9dfc-ad850fe47cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_username</value>
      <webElementGuid>bd01c94b-e2cb-4b31-8ec6-be70b10273ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a57812215e19a1eb1aff0815b4401c5c</value>
      <webElementGuid>35ca86ee-6222-435e-b0fe-9af3784910c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_username']</value>
      <webElementGuid>973ea746-f5a7-4d49-a51d-d55b42b2de5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_username']</value>
      <webElementGuid>3783067b-3742-4613-b0a1-16612da0d060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username' and @placeholder = 'No.HP / Username' and @id = 'id_username']</value>
      <webElementGuid>55ce0273-7b8d-42af-81c6-d90dfeee9170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
