<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Visit Site (5)</name>
   <tag></tag>
   <elementGuidId>e6fd46d0-61cf-4903-9419-71d0e7a2cb5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.rounded-md</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Visit Site&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5a3b4e23-9fe3-43aa-97ec-cb91648597ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8097593a-0cdd-4a75-a5ab-1ce51ec89bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center gap-1.5 whitespace-nowrap rounded-md focus:outline-hidden focus-visible:ring-4 disabled:cursor-default disabled:opacity-50 not-disabled:active:scale-97 ease-out transition-transform duration-150 border-accent-600 bg-form text-accent-600 focus-visible:ring-focus-accent not-disabled:hover:border-accent-700 not-disabled:hover:bg-accent-500/10 not-disabled:hover:text-accent-700 not-disabled:active:border-accent-700 not-disabled:active:bg-accent-500/15 not-disabled:active:text-accent-700 h-9 border px-3 text-sm font-medium font-sans</value>
      <webElementGuid>bead37ed-5d5b-4a77-b892-c4dd72aefccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-appearance</name>
      <type>Main</type>
      <value>outlined</value>
      <webElementGuid>4880f002-4be5-4615-8a5e-694304a1a2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4ad8fcfb-8768-42cb-8e4b-94f03db26108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>96ebad35-1039-41b1-9e05-e32a0c92580a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-priority</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>b4496d96-d64c-4329-82ba-a19040ef1e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97bc2956-4722-4cd6-9a69-e96ded382433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visit Site</value>
      <webElementGuid>82617c9c-877d-482a-90d9-b53fe3814798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-71f8a8fedf9c2dc5193275dfde8d7c8a</value>
      <webElementGuid>2cc06c26-f0d8-47e9-ba27-db7cc18a5b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ')]</value>
      <webElementGuid>e460a5f9-1531-4215-b5e1-06cd39226198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-md ')]</value>
      <webElementGuid>12d9e48e-9a01-404b-86ca-5647b29646bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Visit Site' or . = 'Visit Site')]</value>
      <webElementGuid>69d34494-11f3-400f-8641-d3adf3b76835</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
