<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk (1)</name>
   <tag></tag>
   <elementGuidId>97ea9334-597f-433d-8cde-618033285cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/login/']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/login\/&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Masuk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9cc7a09c-aa43-4d38-bb07-c88cfc3ecba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login/</value>
      <webElementGuid>3e816b53-9e6c-4762-909c-6e50a7292a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-5 py-2 text-sm font-semibold text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors no-underline</value>
      <webElementGuid>927b1a65-1a3c-495b-a233-ffc577fa40c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Masuk
            </value>
      <webElementGuid>f7d387ea-abf0-463f-bfcb-1b3ae2808a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d8c14059a3fd8ca5d439a509ca541c98</value>
      <webElementGuid>e8a188ac-6c05-4ab7-b2e0-33ce91243d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/login/']</value>
      <webElementGuid>d4113b92-e94e-479f-83ba-1e77b2c58bf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/login/']</value>
      <webElementGuid>d58e43ab-eb7c-4456-949d-1d9438c36e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login/' and (text() = '
                Masuk
            ' or . = '
                Masuk
            ')]</value>
      <webElementGuid>c70d9a4c-eeb1-4670-979c-7423e4a99a5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
