<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk (5)</name>
   <tag></tag>
   <elementGuidId>033f27dd-cafb-4840-b7a3-f32a38e8daa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = '/login/']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;\/login\/&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Masuk&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>715eab04-91ff-4d5c-ad74-2c47e1ad079c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login/</value>
      <webElementGuid>312e297d-eac8-4d92-952f-3f67b3d4d599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-5 py-2 text-sm font-semibold text-gray-700 border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors no-underline</value>
      <webElementGuid>3963668a-7cd1-42f8-aaf3-516db4ae81b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Masuk
            </value>
      <webElementGuid>8eb0131e-3bd2-4e5c-aafa-3c2133f67ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d8c14059a3fd8ca5d439a509ca541c98</value>
      <webElementGuid>c8de855b-45bf-4111-8a79-2f2c08876b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = '/login/']</value>
      <webElementGuid>e92dcb1a-6ab6-4537-b50c-4c9f13986a56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = '/login/']</value>
      <webElementGuid>2f3130f9-9f31-478b-affa-2a623418ac5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login/' and (text() = '
                Masuk
            ' or . = '
                Masuk
            ')]</value>
      <webElementGuid>1490e0f0-dab5-4c58-8e86-26452fb88d53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
