<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>b3a6cf8a-6f13-4310-9a7d-099dae8ffde0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Edit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-lokasi=&quot;aul&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-lokasi = 'aul']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8756c52e-61c5-4fd3-8794-169a233741b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>openAgendaModal(this)</value>
      <webElementGuid>6b2dd8a7-0a28-4a42-aaa0-d31980f2d7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-edit</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04582ec6-42e2-468b-b1d2-20a7f658222f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>caa64e31-b9e4-44f1-b7d0-a149009b962a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-judul</name>
      <type>Main</type>
      <value>rapat</value>
      <webElementGuid>3989c2c7-1200-447d-848e-c7d4c1812366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tanggal</name>
      <type>Main</type>
      <value>2026-05-28</value>
      <webElementGuid>024a64e1-2bdf-4ca0-8bea-0f910f2778c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-waktu-mulai</name>
      <type>Main</type>
      <value>08:09</value>
      <webElementGuid>54ae8d33-cc11-49ec-9023-091be9c023a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-waktu-selesai</name>
      <type>Main</type>
      <value>09:09</value>
      <webElementGuid>4d1dea79-6611-44fa-af74-6447c0788f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lokasi</name>
      <type>Main</type>
      <value>aul</value>
      <webElementGuid>677c75eb-c6bf-40e0-843c-f5ae9e2a1858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-keterangan</name>
      <type>Main</type>
      <value>untukrapat</value>
      <webElementGuid>5e34db7e-ada3-4c9f-8cfe-10d03f81eded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b910f396-e9dc-40b2-9000-015137a5bd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center w-8 h-8 rounded-lg bg-[#FEF3C7] hover:bg-[#FDE68A] text-[#D97706] transition-all</value>
      <webElementGuid>ad46febe-bf59-476a-9742-ce8ced859047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>25ddfc6a-86ba-4578-97bf-70746ec2436e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d7df3139c0c6e160ca0e8912581f8e77</value>
      <webElementGuid>8df4f128-7793-4ba3-8422-381d1ab1f741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-lokasi = 'aul']</value>
      <webElementGuid>d8a0275a-626c-40f7-94ee-266290d29d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-lokasi = 'aul']</value>
      <webElementGuid>f27b02c5-631d-4758-a9fa-83bbd88eec8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Edit']</value>
      <webElementGuid>24433674-1cba-4aaf-9c5a-a761fd9c287d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-lokasi = 'aulasekolah']</value>
      <webElementGuid>4bbfe538-f42c-414e-b99d-e951f06d7050</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
