<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_modal-tanggal</name>
   <tag></tag>
   <elementGuidId>12c4c094-aa20-49a7-a4d8-acca30bf00b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-tanggal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'modal-tanggal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>07f04af5-382c-425c-9def-213938969348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>0417c593-de09-4845-8825-9d37f03139d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tanggal</value>
      <webElementGuid>e2ec5cca-cd9c-4436-b732-efd3fc38b1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-tanggal</value>
      <webElementGuid>4b83b430-6752-4cd8-9c70-4e13ab9d37f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-[#00A74D]/20 focus:border-[#00A74D] outline-none transition-all</value>
      <webElementGuid>d986e6dc-a67e-4efc-91ae-5c3ceb8e93b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3ad00bcaca636e117f144a247168414e</value>
      <webElementGuid>4dbf320d-a159-4a99-a2b2-668f74b0079d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'modal-tanggal']</value>
      <webElementGuid>0a81acb9-94c2-421e-9978-20573ef97558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'modal-tanggal']</value>
      <webElementGuid>2b4bf43c-aba8-4ce9-81d0-1525c85c2965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'tanggal' and @id = 'modal-tanggal']</value>
      <webElementGuid>c815c00a-cf12-4a62-a128-1d4d7bf48887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
