<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_modal-waktu-mulai</name>
   <tag></tag>
   <elementGuidId>dd97bb04-64ee-4b1b-a1cc-c48c74352605</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-waktu-mulai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'modal-waktu-mulai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ab434df-ea94-4485-9870-ef15494cd32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>c74a5751-3d14-4084-95cb-3fd886b440c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>waktu_mulai</value>
      <webElementGuid>023c87cd-9421-408a-aa64-f9377fc814c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-waktu-mulai</value>
      <webElementGuid>01602d55-29a7-4fe0-ab22-5d2fec3354d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-[#00A74D]/20 focus:border-[#00A74D] outline-none transition-all</value>
      <webElementGuid>ef4cb566-3da8-4105-b567-d966b50ebc55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-20c59f987e3997ae8e7ddc8be053f623</value>
      <webElementGuid>9fd091ad-54ff-4a7a-ad0f-94c2c5fb094a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'modal-waktu-mulai']</value>
      <webElementGuid>e64b4e68-dc17-41af-85e4-ded8fe6cfe9f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'modal-waktu-mulai']</value>
      <webElementGuid>b270eb1f-979f-4ed7-a084-73e49b2fb294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'time' and @name = 'waktu_mulai' and @id = 'modal-waktu-mulai']</value>
      <webElementGuid>0ae08edf-61f0-448f-add8-2f65e0af4dce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
