<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_modal-waktu-selesai</name>
   <tag></tag>
   <elementGuidId>1182cc9b-6525-4741-a0c8-f9413b1f35df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-waktu-selesai</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'modal-waktu-selesai']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>548a654d-de96-4ea0-9aaf-5f3cd33ebfd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>f5b705c1-dde4-476d-a7c2-28047964b716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>waktu_selesai</value>
      <webElementGuid>527f6938-fca8-4356-9ad6-d88224a5c838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-waktu-selesai</value>
      <webElementGuid>4837e83e-f4f6-4234-90ce-09b75d3e067f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-[#00A74D]/20 focus:border-[#00A74D] outline-none transition-all</value>
      <webElementGuid>283d4843-c5da-4769-afc7-964141fe26a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8b9353ee1fa53ec32d943c38ad5dda62</value>
      <webElementGuid>0e84af8c-debc-4c81-b375-e036180f1c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'modal-waktu-selesai']</value>
      <webElementGuid>2d47baa1-f041-4008-8798-96275f9790a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'modal-waktu-selesai']</value>
      <webElementGuid>7ea0c7fa-1987-4042-b8cd-fa35bdf83da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'time' and @name = 'waktu_selesai' and @id = 'modal-waktu-selesai']</value>
      <webElementGuid>ddac4e98-3a74-4103-a2d1-af7308a9100b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
