<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contoh_ Aula Sekolah</name>
   <tag></tag>
   <elementGuidId>2bbf3772-077f-42fa-acd3-7024f26c9f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'lokasi' and @id = 'modal-lokasi' and @placeholder = 'Contoh: Aula Sekolah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-lokasi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'modal-lokasi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56d16754-06f8-4077-af9d-6a6988a95ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1e2508b-10be-44cb-a2a7-a2855c5dc745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lokasi</value>
      <webElementGuid>15781100-fd27-443c-b9a8-5ca410760e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-lokasi</value>
      <webElementGuid>b38b6935-fffe-4282-a4b7-d39c98f66cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-[#00A74D]/20 focus:border-[#00A74D] outline-none transition-all</value>
      <webElementGuid>238ba67a-c1d5-49f6-8280-8b128ed0aea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Aula Sekolah</value>
      <webElementGuid>0d3d6f27-b665-4f9c-a137-9fa15873bfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-df0727e862bbe253dde8f10fb4ae07af</value>
      <webElementGuid>24e50114-a1af-4708-9742-056c2183de92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'modal-lokasi']</value>
      <webElementGuid>ceddab73-c6f6-45d7-8038-c6b19d4aba38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'modal-lokasi']</value>
      <webElementGuid>40365404-4085-421d-92d7-1a78a8f7ab6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lokasi' and @id = 'modal-lokasi' and @placeholder = 'Contoh: Aula Sekolah']</value>
      <webElementGuid>3a3c5ed2-48e7-4b30-b357-414135d5f3fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
