<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Detail kegiatan</name>
   <tag></tag>
   <elementGuidId>74d42d0b-856e-4b9e-ad7e-5f3457cc820a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-keterangan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'modal-keterangan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bdd62717-1777-4838-a2f3-21e48e7d7ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>3b024cf8-3633-492f-b41e-5222fd9bcea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-keterangan</value>
      <webElementGuid>cbc68274-c5d4-450d-a78c-280e9c19e3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4426fbd8-18d0-4df8-9153-9c7ad51cc08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-2.5 bg-slate-50 border border-slate-200 rounded-xl text-sm focus:ring-2 focus:ring-[#00A74D]/20 focus:border-[#00A74D] outline-none transition-all</value>
      <webElementGuid>69b3e8e7-b755-4010-9e40-315a4bc0d7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Detail kegiatan...</value>
      <webElementGuid>f2be10bd-f2c2-4d44-a15c-6258208b4a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-73d2e2d4b3aaaccbae014d5be6e8d5af</value>
      <webElementGuid>8485dd52-b537-4f45-8b1a-8411094b1b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'modal-keterangan']</value>
      <webElementGuid>fc4fa441-06c6-4c4e-8465-61bd0c9c1b96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'modal-keterangan']</value>
      <webElementGuid>490d9ba5-3a74-4cb6-bcdb-4ee554503c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'keterangan' and @id = 'modal-keterangan' and @placeholder = 'Detail kegiatan...']</value>
      <webElementGuid>ec1aac72-b10e-4de1-992c-ce40043eb040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
