<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_muridSubmitText</name>
   <tag></tag>
   <elementGuidId>de023061-526b-4c0f-a119-8e1771f905fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#muridSubmitText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'muridSubmitText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f4293ce-f4df-4554-839e-853fa4c36c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>718a01c3-e2c6-499d-af59-4e06d3dce9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>muridSubmitText</value>
      <webElementGuid>a1feaf95-34d2-434a-a8a7-cf36c705e325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-primary</value>
      <webElementGuid>7ecbc6af-5b46-4934-b557-05516ce075ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>34978c52-ac8a-44e2-bad5-5856195d4aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-479b27c594291ade4f0639ef71b98b52</value>
      <webElementGuid>68b518e8-6664-45b6-b633-7a178b5f001d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'muridSubmitText']</value>
      <webElementGuid>2b9118cf-9290-45b5-9899-414b8f81642d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'muridSubmitText']</value>
      <webElementGuid>92cd23e6-7965-468f-9b9a-5106da2d2c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'muridSubmitText' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>ff269ca5-ff8f-4372-86a7-01e9b7288c73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
