<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama lengkap siswa</name>
   <tag></tag>
   <elementGuidId>0e38d5d4-11c9-4e4f-a317-f69d087629dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_nama_lengkap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_nama_lengkap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>734c774f-52a0-46c5-ae3e-d2ae63613b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7138a4dd-9538-4e11-b525-aed484c4db8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_lengkap</value>
      <webElementGuid>34e76476-248d-4065-b0df-1deeb8aa0735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_nama_lengkap</value>
      <webElementGuid>a95a0c98-cb92-4d49-8981-dc457e52703b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5f747122-da3a-41cc-8cd7-fb768ad86eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama lengkap siswa</value>
      <webElementGuid>361f7656-1dab-4d03-8202-21e16727f38e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0991b2e56589fae3f3da650ba0627e05</value>
      <webElementGuid>c33d01ff-d0f1-4c93-a7c4-3ac8c71d2e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_nama_lengkap']</value>
      <webElementGuid>4069d170-5d04-4126-b7c7-486242e6924b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_nama_lengkap']</value>
      <webElementGuid>e617e9a7-926b-4408-ba2e-d2e27f238662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nama_lengkap' and @id = 'id_nama_lengkap' and @placeholder = 'Nama lengkap siswa']</value>
      <webElementGuid>e77afcd8-f417-4c2c-8be0-bda52836aaf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
