<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Lahir</name>
   <tag></tag>
   <elementGuidId>71776fab-2b54-4367-bd01-a6b4a4ff689d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_tanggal_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_tanggal_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf63cada-d5ec-4d84-af16-3f25a0db740b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>e3355cff-12c4-4676-a407-76e98d2556cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tanggal_lahir</value>
      <webElementGuid>613064fc-fa81-4bb7-a3c3-053a9607b950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_tanggal_lahir</value>
      <webElementGuid>1704854c-41d4-4d3e-a912-e6ecf4df5d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c1b46416-3302-4618-a038-0084cec1bab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3dd29a9845216d6223df21b35a2c2cee</value>
      <webElementGuid>1a370e54-83c2-496d-acc2-248aa54f8924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_tanggal_lahir']</value>
      <webElementGuid>cee1100e-12f0-470e-88f9-e7e2f7249f76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_tanggal_lahir']</value>
      <webElementGuid>bc81188b-f7ab-405c-899e-fa9fe384854f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'date' and @name = 'tanggal_lahir' and @id = 'id_tanggal_lahir']</value>
      <webElementGuid>41e52bd1-25b9-4bab-95f9-910c8d2c535a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
