<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tempat lahir</name>
   <tag></tag>
   <elementGuidId>0164fb04-30f1-4030-9df8-31b204bc7c4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_tempat_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_tempat_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d58507fb-7000-4c2c-a82c-a3b817a1305b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87a893b4-cf50-492d-89cc-0cab7a4f7d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempat_lahir</value>
      <webElementGuid>022f9720-10ae-4767-88b3-ffbb95c65db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_tempat_lahir</value>
      <webElementGuid>3e8b6f6c-aef6-4abc-b7f2-67356985ee9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>386843fc-2451-426a-aab5-16a39da3cc1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tempat lahir</value>
      <webElementGuid>64fd2407-ecd1-433b-bcde-1986fe9f023e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2ab7921b17c3c6733bc21f02523e299b</value>
      <webElementGuid>fe2b6304-2fed-478f-964b-9f9443e61237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_tempat_lahir']</value>
      <webElementGuid>fe906644-c9a2-4dbf-b7c6-7d9200030d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_tempat_lahir']</value>
      <webElementGuid>886398f3-66c3-4836-b1c3-8d6612518091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tempat_lahir' and @id = 'id_tempat_lahir' and @placeholder = 'Tempat lahir']</value>
      <webElementGuid>58f0c633-a0cf-42dc-b8dc-eef671ec28d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
