<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Induk Siswa</name>
   <tag></tag>
   <elementGuidId>8ee9e887-7fb3-4366-886e-b1b8e01f7eaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_nis</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'id_nis']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31363695-e2dd-4c09-a3fc-53cbb6339bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cb61ea9f-0586-437c-b7b1-0e8e1232e098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nis</value>
      <webElementGuid>abca33c3-b337-41ea-9103-df4989a63d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_nis</value>
      <webElementGuid>6184dfe8-7e29-4194-8847-6cf1575f253f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1534d92a-9601-4278-9b78-3e1161344699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Induk Siswa</value>
      <webElementGuid>d2cbbed2-c2f3-43c1-9611-a11dcdcf4a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0991e40513b0a26afc554ea5a8b4f7f2</value>
      <webElementGuid>e8305838-2376-4c0b-87ef-0425f6484aec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'id_nis']</value>
      <webElementGuid>a7e689bb-6dc3-48bb-94e3-7aa067689a58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'id_nis']</value>
      <webElementGuid>70daf944-7244-42e7-9b0b-bc6e424e081d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nis' and @id = 'id_nis' and @placeholder = 'Nomor Induk Siswa']</value>
      <webElementGuid>629d121f-bbe8-4d98-8a8b-c696af7adb82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
