<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contoh_ Budi Susanto</name>
   <tag></tag>
   <elementGuidId>7e8e49f2-11f9-47a0-b6d5-fab04bed37a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#waliSearchInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'waliSearchInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c48e7bd0-c8a2-43a0-af58-83d6ce87cd81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf152a89-ad0c-4325-806f-0ea5fa6e7754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>waliSearchInput</value>
      <webElementGuid>6db965bc-b443-4d9d-8d19-f48e74bc0760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b0060648-a976-45d4-94af-ccaf1e315c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>558a4e06-9ace-4587-8b59-95e9bc30165d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Budi Susanto...</value>
      <webElementGuid>8b39e9e6-e05f-453a-97c0-dc79582a2cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fd9cf377010f653771216662e35ef0cc</value>
      <webElementGuid>d2c1be23-89fd-42cb-9fd0-d098bb0ad296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'waliSearchInput']</value>
      <webElementGuid>d478c0f6-874f-4c42-904d-deaedbb88c2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'waliSearchInput']</value>
      <webElementGuid>1fe7d3dc-3523-4271-a2df-c82b8815cdf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'waliSearchInput' and @placeholder = 'Contoh: Budi Susanto...']</value>
      <webElementGuid>95a0682f-5e65-452d-aab5-3901e8c3b7d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
